### PR TITLE
Feature design teardown

### PR DESCRIPTION
**Pull request by mugberto**
Project: Design teardown

In this project we:
- Create a grayscale heatmap of the Smash Magazine website
- Use  grid, flexbox, and float to create the layout

Fix after TSE feedback:
- HTML validation errors

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

Your project looks awesome.🚀🚀

You are just one step away from a thumbs up.

- [ ] Required - Kindly fix the HTML validation errors that exist in your HTML code. Use this [HTML validator tool](https://validator.w3.org/nu/#file) to check and fix the errors.

Kindly fix these issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by sumancrest0001** [comment]
**Project Approved.
Awesome Work TEAM. :clap:  :clap:** 
It's a green signal from my side as it ticks all the requirements. Go a head and merge this branch to the master branch.
All the best with the next project.
**Happy coding :+1:** 
mission

**Comment by Rumbie-Mudzie7** [comment]
Thank You.

**Pull request merged**
